export const GAME_INITIALIZING = 'game:initialize'
export const GAME_INITIALIZED = 'game:initialized'
export const GAME_STARTING = 'game:start'
export const GAME_STARTED = 'game:started'
export const GAME_PAUSING = 'game:pausing'
export const GAME_PAUSED = 'game:paused'
export const GAME_RESUMING = 'game:resuming'
export const GAME_RESUMED = 'game:resumed'
export const GAME_TERMINATING = 'game:terminating'
export const GAME_TERMINATED = 'game:terminated'

export const ACTOR_VISITING = 'actor:visiting'
export const ACTOR_ARRIVED = 'actor:arrived'
export const ACTOR_DEPARTING = 'actor:departing'