export const GAME_INITIALIZING = 'game:initialize'
export const GAME_INITIALIZED = 'game:initialized'
export const GAME_STARTING = 'game:start'
export const GAME_STARTED = 'game:started'
export const GAME_PAUSING = 'game:pausing'
export const GAME_PAUSED = 'game:paused'
export const GAME_RESUMING = 'game:resuming'
export const GAME_RESUMED = 'game:resumed'
export const GAME_TERMINATING = 'game:terminating'
export const GAME_TERMINATED = 'game:terminated'

// ACTOR_VISITING indicates that a timetraveler
export const TIME_TRAVELER_VISITING = 'timetraveler:visiting'
export const TIME_TRAVELER_ARRIVED = 'timetraveler:arrived'
export const TIME_TRAVELER_DEPARTING = 'timetraveler:departing'